version: "3.8"
services:
  db:
    image: "postgres:14.0"
    ports:
      - "5432:5432"
    volumes:
      - ~/Devel/data/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=kabapg
