server:
  port: 8200
spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: ${POSTGRESQL_URL:jdbc:postgresql://ddbrgbl0-pg.postgres.database.azure.com:5432/postgres}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRESQL_USERNAME:dbruser@ddbrgbl0-pg}
    password: ${POSTGRESQL_PASSWORD:uVbcynv3heQQ9yaD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create

gst:
   # Cron de lecture ecriture qui s'execute toutes les 15 minutes
   synchro-cron: ${DAILY_BATCH_CRON:0 */15 * * * *}
   # Cron de verification pour la suppression des archives qui s'execute tous les jours a minuit
   #clean-achives-cron: ${ARCHIVES_DAILY_BATCH_CRON:0/20 * * * * *}
   clean-achives-cron: ${ARCHIVES_DAILY_BATCH_CRON:0 0 * * * *}
   
## Batch config
# Nombre de donnees par traitement lors du l'execution du batch
batch:
  chunk: ${BATCH_CHUNK:100}
  # nombre de jours maximums pour la retention des archives
  archives-nb-max-days: ${ARCHIVE_NB_MAX_DAYS:10}
  archives-directory: ${ARCHIVES_DIRECTORY:src/main/resources/data/archives/}
  vehicle-json-path: ${VEHICULE_JSON_PATH:src/main/resources/data/vehicles.json}
  journey-json-path: ${JOURNEY_JSON_PATH:src/main/resources/data/journeys.json}
 
