spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: kabapg
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create


## Batch config
# Nombre de donnees par traitement lors du l'execution du batch
batch:
  chunk: 100
  # Cron de lecture ecriture qui s'execute toutes les 20 secondes
  read-write:
    cron: 0 0/5 * * * *
  vehicle-json-path: src/main/resources/data/vehicles.json
  journey-json-path: src/main/resources/data/journeys.json

